# Generated by Django 4.1.7 on 2023-04-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('des', models.TextField(max_length=255)),
                ('categories', models.CharField(choices=[('food', 'food'), ('beauty', 'beauty'), ('lifestyle', 'lifestyle'), ('fashion', 'fashion')], max_length=150)),
                ('pic', models.FileField(default='sad.jpeg', upload_to='blog_photos')),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
